volumes:
  static:
  media:

services:
  backend:
    image: kereot/foodgram-back
    container_name: foodgram-backend
    env_file: .env
    restart: unless-stopped
    volumes:
      - static:/static
      - media:/app/media
      - ./data:/data
    networks:
      - default
      - proxy
  frontend:
    env_file: .env
    image: kereot/foodgram-front
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    image: kereot/foodgram-proxy
    container_name: foodgram-nginx
    env_file: .env
    restart: unless-stopped
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - backend
      - frontend
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
