volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14
    env_file: .env
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kereot/foodgram-back
    env_file: .env
    restart: unless-stopped
    volumes:
      - static:/static
      - media:/app/media
      - ./data:/data
    depends_on:
      - db
  frontend:
    env_file: .env
    image: kereot/foodgram-front
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    image: kereot/foodgram-proxy
    env_file: .env
    ports:
      - 10000:80
    restart: unless-stopped
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - backend
      - frontend
