PAGE_SIZE = 6

DEFAULT_MAX_LENGTH = 255

USER_CHAR_FIELD_MAX_LENGTH = 150
USER_EMAIL_FIELD_MAX_LENGTH = 254

TAG_NAME_SLUG_FIELD_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256

SHORT_CODE_MAX_LENGTH = 6

VISUAL_NAME_LIMIT = 25

USERNAME_REGEX = r'[\w.@+-]'
SLUG_REGEX = r'^[-a-zA-Z0-9_]+$'

SHOPPING_LIST_TEXT = 'Список покупок'
