# Generated by Django 5.2.14 on 2026-05-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='blank', upload_to='recipes/images/', verbose_name='Картинка, закодированная в Base64'),
            preserve_default=False,
        ),
    ]
