# Generated by Django 5.2.14 on 2026-09-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_publish_recipes',
            field=models.BooleanField(default=False, verbose_name='Может публиковать рецепты'),
        ),
    ]
